version: '3.4'

services:

  TravelCoDb:
   image: mcr.microsoft.com/mssql/server
  redis:
   image: redis




  travelcoapi:
    image: travelcoapi
    container_name: travelco-container
    build:
      context: .
      dockerfile: TravelCoAPI/Dockerfile
volumes:
   redis_volume:
   TravelCoDb_volume: 