version: '3.4'
services:
  redis:

   ports:
    - 6379:6379
   
   volumes:
    - redis_volume:/data


 

  travelcoapi:
    environment:
     
      - ASPNETCORE_HTTP_PORTS=8080
      
    ports:
      - "5080:8080"
    depends_on:
      - redis
