version: '3.4'
services:
  redis:

   ports:
    - 6379:6379
   
   volumes:
    - redis_volume:/data

  TravelCoDb:
   container_name: TravelCoDb
   restart: always
   ports:
     - "1433:1433"
   volumes:
    - TravelCoDb_volume:/var/opt/mssql/data
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Yg231101.


  travelcoapi:
    environment:
     
      - ASPNETCORE_HTTP_PORTS=8080
      
    ports:
      - "5080:8080"
    depends_on:
      - redis
