using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Travel.Enums
{
    public enum HomeServiceTypes
    {
        Bathroom,
        HairDryer,
        CleaningProducts,
        Shampoo,
        Bidet,
        HotWater,
        BedroomAndLinen,
        InUnitWasher,
        BasicSupplies,
        TowelsAndToiletPaper,
        Hangers,
        BedSheets,
        CottonBedLinens,
        ExtraPillowsAndBlankets,
        BlackoutCurtains,
        Iron,
        Safe,
        ClothingStorage,
        Entertainment,
        HDTVAndNetflix,
        Family,
        Crib,
        PackNPlay,
        ChildrensBooksAndToys,
        HighChair,
        OutdoorPlayArea,
        HeatingAndCooling,
        CentralAC,
        Heating,
        HomeSecurity,
        SmokeDetector,
        CarbonMonoxideAlarm,
        FireExtinguisher,
        InternetAndOffice,
        Wifi,
        PrivateWorkspace,
        KitchenAndDining,
        Kitchen,
        GuestsCanCook,
        Refrigerator,
        Microwave,
        BasicCookingSupplies,
        PotsAndPans,
        Cutlery,
        Bowls,
        Chopsticks,
        Plates,
        Cups,
        Freezer,
        Dishwasher,
        StainlessSteelGasStove,
        Oven,
        ElectricKettle,
        CoffeeMaker,
        WineGlasses,
        BakingSheet,
        Blender,
        Coffee,
        LocationFeatures,
        Waterfront,
        PrivateBeachAccess,
        GuestsCanEnjoyNearbyBeach,
        FacilityAccess,
        GuestsCanUseNearbyResortFacilities,
        Outdoor,
        PrivateDeckOrBalcony,
        FullyFencedPrivateBackyard,
        OutdoorSpaceUsuallyLawnCovered,
        GardenFurniture,
        OutdoorDiningArea,
        CharcoalWoodBarbecue,
        BeachEssentials,
        BeachTowels,
        Umbrella,
        BeachBlanket,
        SnorkelingEquipment,
        ParkingAndFacilities,
        FreeParkingInBuilding,
        FreeStreetParking,
        Elevator,
        ElevatorWithAtLeast52InchDepthAnd32InchWideDoor,
        Services,
        LuggageDropoffAllowed,
        EarlyOrLateCheckin,
        LongTermStaysAllowed,
        AllowedForStays28DaysOrMore,
        SelfCheckIn,
      

    }
}
